id: PF0496944
initial_creation_type: input
source_metadata:
  title: Bhikṣuṇī Lakṣmī
  language: bo
  description: 'Texts by and about the Kashmiri nun Bhikṣuṇī Lakṣmī/Lakṣmīṅkarā, known
    to Tibetans as Gelongma Palmo (dge slong ma dpal mo):'
  volume:
    031e782582c54d2491fad91ca9d78a85:
      title: Praise of Noble Avalokiteśvara
      parent: Praise
    d1218b10b0614f0f93e4dd74b5139837:
      title: Praise of Noble Avalokiteśvara (Tengyur version)
      parent: Praise
    920bf16ca3d04d8699565d906d719996:
      title: Seven-Branch Offering to Tārā
      parent: Seven-Branch Offering
created_at: '2022-03-01T02:16:24.636760'
last_modified_at: '2022-03-01T02:16:24.636762'
statistics:
  total_words: 1104
  total_non_words: 59
quality:
  non_words_ratio: 0.05
